package com.jfinal.model;

import com.jfinal.model.base.BaseOcmUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OcmUser extends BaseOcmUser<OcmUser> {
	public static final OcmUser dao = new OcmUser().dao();
	
}
