package com.jifnal.model;

import com.jfinal.model.BaseFeihong;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Feihong extends BaseFeihong<Feihong> {
	public static final Feihong dao = new Feihong().dao();
}
