package com.jifnal.model;

import com.jfinal.model.BaseIndexPage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IndexPage extends BaseIndexPage<IndexPage> {
	public static final IndexPage dao = new IndexPage().dao();
}
